### ISSUE TITLE
Update how Jira issues are parsed and shown in Octopus

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/JiraIssueTracker#12]
We've had reports from multiple customers that their Jira issues isn't being included in the list of work items in Octopus.

After discussions in the team we've decided:
- We'll make the regular expression we use to parse Jira issues from comments included in the package metadata less restrictive, this will allow a number of extra scenarios we've seen customers using to be supported.
- We will only show the list of work items in Octopus if the Jira extension is enabled and a username and password has been configured in Octopus.

**Comment by slewis74** [comment]
Another related issue with the RegEx, https://secure.helpscout.net/conversation/898635061/46967?folderId=2845830
