### ISSUE TITLE
Jira configuration changes to support Jira Server/Cloud and differences in required settings

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/JiraIssueTracker#6]
We should add a new config setting to specify if you're using Jira Cloud or Jira Server so that we can dynamically show/hide the other configuration settings and also determine if we should show/hide log entries and/or environment settings.

This will require some changes to our extension architecture to support dependent properties and values

**Comment by slewis74** [comment]
Closed early, still have a couple of updates to do now the new config field exists.

**Comment by slewis74** [comment]
Now server has the updated reference
